using AutoMapper;

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using V.SMART.Shared.Data.HumanResource.Salary;
using V.SMART.Shared.ViewModels.HumanResourceViewModel.SalaryViewModel;

namespace V.SMART.Shared.Mappings.HumanResource.EmployeeSalaryProfile
{
    public class SalaryProfile : Profile
    {
        public SalaryProfile()
        {
            // ========================
            // VM → Entity
            // ========================
            CreateMap<SalaryVM, Salary>()
                .ForMember(dest => dest.RowId, opt => opt.MapFrom(src => src.RowId))
                .ForMember(dest => dest.SalYear, opt => opt.MapFrom(src => src.SalYear))
                .ForMember(dest => dest.SalMonth, opt => opt.MapFrom(src => src.SalMonth))
                .ForMember(dest => dest.SalDate, opt => opt.MapFrom(src => src.SalDate))
                .ForMember(dest => dest.StaffId, opt => opt.MapFrom(src => src.StaffId))
                .ForMember(dest => dest.Dept, opt => opt.MapFrom(src => src.Dept))
                .ForMember(dest => dest.PayableDays, opt => opt.MapFrom(src => src.PayableDays))
                .ForMember(dest => dest.WorkingDays, opt => opt.MapFrom(src => src.WorkingDays))
                .ForMember(dest => dest.LeaveDays, opt => opt.MapFrom(src => src.LeaveDays))
                .ForMember(dest => dest.OT, opt => opt.MapFrom(src => src.OT))
                .ForMember(dest => dest.Basic, opt => opt.MapFrom(src => src.Basic))
                .ForMember(dest => dest.EarnedBasic, opt => opt.MapFrom(src => src.EarnedBasic))
                .ForMember(dest => dest.DA, opt => opt.MapFrom(src => src.DA))
                .ForMember(dest => dest.EarnedDA, opt => opt.MapFrom(src => src.EarnedDA))
                .ForMember(dest => dest.IsOTunderBasic, opt => opt.MapFrom(src => src.IsOTunderBasic))
                .ForMember(dest => dest.OT_times_now, opt => opt.MapFrom(src => src.OT_times_now))
                .ForMember(dest => dest.EarnedOT, opt => opt.MapFrom(src => src.EarnedOT))
                .ForMember(dest => dest.IsAttBonus, opt => opt.MapFrom(src => src.IsAttBonus))
                .ForMember(dest => dest.EarnedAttBonus, opt => opt.MapFrom(src => src.EarnedAttBonus))
                .ForMember(dest => dest.IsHRAPerDay, opt => opt.MapFrom(src => src.IsHRAPerDay))
                .ForMember(dest => dest.IsHRAPerMonth, opt => opt.MapFrom(src => src.IsHRAPerMonth))
                .ForMember(dest => dest.HRA, opt => opt.MapFrom(src => src.HRA))
                .ForMember(dest => dest.EarnedHRA, opt => opt.MapFrom(src => src.EarnedHRA))
                .ForMember(dest => dest.IsTAPerDay, opt => opt.MapFrom(src => src.IsTAPerDay))
                .ForMember(dest => dest.IsTAPerMonth, opt => opt.MapFrom(src => src.IsTAPerMonth))
                .ForMember(dest => dest.TA, opt => opt.MapFrom(src => src.TA))
                .ForMember(dest => dest.EarnedTA, opt => opt.MapFrom(src => src.EarnedTA))
                .ForMember(dest => dest.EA, opt => opt.MapFrom(src => src.EA))
                .ForMember(dest => dest.SplAllow, opt => opt.MapFrom(src => src.SplAllow))
                .ForMember(dest => dest.EarnedSplAllow, opt => opt.MapFrom(src => src.EarnedSplAllow))
                .ForMember(dest => dest.LTA, opt => opt.MapFrom(src => src.LTA))
                .ForMember(dest => dest.MR, opt => opt.MapFrom(src => src.MR))
                .ForMember(dest => dest.TotalEarnings, opt => opt.MapFrom(src => src.TotalEarnings))
                .ForMember(dest => dest.IsPF, opt => opt.MapFrom(src => src.IsPF))
                .ForMember(dest => dest.EarnedPF, opt => opt.MapFrom(src => src.EarnedPF))
                .ForMember(dest => dest.IsESI, opt => opt.MapFrom(src => src.IsESI))
                .ForMember(dest => dest.EarnedESI, opt => opt.MapFrom(src => src.EarnedESI))
                .ForMember(dest => dest.PT, opt => opt.MapFrom(src => src.PT))
                .ForMember(dest => dest.TDS, opt => opt.MapFrom(src => src.TDS))
                .ForMember(dest => dest.Society, opt => opt.MapFrom(src => src.Society))
                .ForMember(dest => dest.Insurance, opt => opt.MapFrom(src => src.Insurance))
                .ForMember(dest => dest.SalAdvance, opt => opt.MapFrom(src => src.SalAdvance))
                .ForMember(dest => dest.Fines, opt => opt.MapFrom(src => src.Fines))
                .ForMember(dest => dest.DamageLoss, opt => opt.MapFrom(src => src.DamageLoss))
                .ForMember(dest => dest.OtherDed, opt => opt.MapFrom(src => src.OtherDed))
                .ForMember(dest => dest.LoanId, opt => opt.MapFrom(src => src.LoanId))
                .ForMember(dest => dest.LoanAmtDed, opt => opt.MapFrom(src => src.LoanAmtDed))
                .ForMember(dest => dest.LoanBalB4, opt => opt.MapFrom(src => src.LoanBalB4))
                .ForMember(dest => dest.TotalDed, opt => opt.MapFrom(src => src.TotalDed))
                .ForMember(dest => dest.NetPay, opt => opt.MapFrom(src => src.NetPay))
                .ForMember(dest => dest.OldBal, opt => opt.MapFrom(src => src.OldBal))
                .ForMember(dest => dest.paidAmt, opt => opt.MapFrom(src => src.paidAmt))
                .ForMember(dest => dest.AttBonus, opt => opt.MapFrom(src => src.AttBonus))
                .ForMember(dest => dest.LoanDedId, opt => opt.MapFrom(src => src.LoanDedId))
                .ForMember(dest => dest.IsDAtoPF, opt => opt.MapFrom(src => src.IsDAtoPF))
                .ForMember(dest => dest.IsPT, opt => opt.MapFrom(src => src.IsPT))
                .ForMember(dest => dest.ESIBankCode, opt => opt.MapFrom(src => src.ESIBankCode))
                .ForMember(dest => dest.ESIBankName, opt => opt.MapFrom(src => src.ESIBankName))
                .ForMember(dest => dest.ESICQDate, opt => opt.MapFrom(src => src.ESICQDate))
                .ForMember(dest => dest.ESICQNo, opt => opt.MapFrom(src => src.ESICQNo))
                .ForMember(dest => dest.ESIDate, opt => opt.MapFrom(src => src.ESIDate))
                .ForMember(dest => dest.ESIPytMode, opt => opt.MapFrom(src => src.ESIPytMode))
                .ForMember(dest => dest.PFBankName, opt => opt.MapFrom(src => src.PFBankName))
                .ForMember(dest => dest.PFCQDate, opt => opt.MapFrom(src => src.PFCQDate))
                .ForMember(dest => dest.PFCQNo, opt => opt.MapFrom(src => src.PFCQNo))
                .ForMember(dest => dest.PFDate, opt => opt.MapFrom(src => src.PFDate))
                .ForMember(dest => dest.PFDepositor, opt => opt.MapFrom(src => src.PFDepositor))
                .ForMember(dest => dest.PFPytMode, opt => opt.MapFrom(src => src.PFPytMode))
                .ForMember(dest => dest.Createdby, opt => opt.MapFrom(src => src.Createdby))
                .ForMember(dest => dest.Createddate, opt => opt.MapFrom(src => src.Createddate))
                .ForMember(dest => dest.Modifiedby, opt => opt.MapFrom(src => src.Modifiedby))
                .ForMember(dest => dest.Modifieddate, opt => opt.MapFrom(src => src.Modifieddate))
                .ForMember(dest => dest.chckOT, opt => opt.MapFrom(src => src.chckOT))
                .ForMember(dest => dest.PH, opt => opt.MapFrom(src => src.PH))
                .ForMember(dest => dest.W, opt => opt.MapFrom(src => src.W))
                .ForMember(dest => dest.LOP, opt => opt.MapFrom(src => src.LOP))
                .ForMember(dest => dest.P, opt => opt.MapFrom(src => src.P))
                .ForMember(dest => dest.O, opt => opt.MapFrom(src => src.O))
                .ForMember(dest => dest.Miscellaneous, opt => opt.MapFrom(src => src.Miscellaneous))
                .ForMember(dest => dest.Others, opt => opt.MapFrom(src => src.Others))
                .ForMember(dest => dest.IsSplAllowPerDay, opt => opt.MapFrom(src => src.IsSplAllowPerDay))
                .ForMember(dest => dest.IsSplAllowPerMonth, opt => opt.MapFrom(src => src.IsSplAllowPerMonth))
                .ForMember(dest => dest.IsMRPerDay, opt => opt.MapFrom(src => src.IsMRPerDay))
                .ForMember(dest => dest.IsMRPerMonth, opt => opt.MapFrom(src => src.IsMRPerMonth))
                .ForMember(dest => dest.IsLTAPerDay, opt => opt.MapFrom(src => src.IsLTAPerDay))
                .ForMember(dest => dest.IsLTAPerMonth, opt => opt.MapFrom(src => src.IsLTAPerMonth))
                .ForMember(dest => dest.IsEAPerDay, opt => opt.MapFrom(src => src.IsEAPerDay))
                .ForMember(dest => dest.IsEAPerMonth, opt => opt.MapFrom(src => src.IsEAPerMonth))
                .ForMember(dest => dest.EarnedLTA, opt => opt.MapFrom(src => src.EarnedLTA))
                .ForMember(dest => dest.EarnedMR, opt => opt.MapFrom(src => src.EarnedMR))
                .ForMember(dest => dest.EarnedEA, opt => opt.MapFrom(src => src.EarnedEA))
                .ForMember(dest => dest.PresentDays, opt => opt.MapFrom(src => src.PresentDays))
                .ForMember(dest => dest.AbsentDays, opt => opt.MapFrom(src => src.AbsentDays))
                .ForMember(dest => dest.Holidays, opt => opt.MapFrom(src => src.Holidays));
               //.ForAllOtherMembers(opt => opt.Ignore());


            // Entity → VM mapping
            CreateMap<Salary, SalaryVM>()
                .ForMember(dest => dest.RowId, opt => opt.MapFrom(src => src.RowId))
                .ForMember(dest => dest.SalYear, opt => opt.MapFrom(src => src.SalYear))
                .ForMember(dest => dest.SalMonth, opt => opt.MapFrom(src => src.SalMonth))
                .ForMember(dest => dest.SalDate, opt => opt.MapFrom(src => src.SalDate))
                .ForMember(dest => dest.StaffId, opt => opt.MapFrom(src => src.StaffId))
                .ForMember(dest => dest.Dept, opt => opt.MapFrom(src => src.Dept))
                .ForMember(dest => dest.PayableDays, opt => opt.MapFrom(src => src.PayableDays))
                .ForMember(dest => dest.WorkingDays, opt => opt.MapFrom(src => src.WorkingDays))
                .ForMember(dest => dest.LeaveDays, opt => opt.MapFrom(src => src.LeaveDays))
                .ForMember(dest => dest.OT, opt => opt.MapFrom(src => src.OT))
                .ForMember(dest => dest.Basic, opt => opt.MapFrom(src => src.Basic))
                .ForMember(dest => dest.EarnedBasic, opt => opt.MapFrom(src => src.EarnedBasic))
                .ForMember(dest => dest.DA, opt => opt.MapFrom(src => src.DA))
                .ForMember(dest => dest.EarnedDA, opt => opt.MapFrom(src => src.EarnedDA))
                .ForMember(dest => dest.IsOTunderBasic, opt => opt.MapFrom(src => src.IsOTunderBasic))
                .ForMember(dest => dest.OT_times_now, opt => opt.MapFrom(src => src.OT_times_now))
                .ForMember(dest => dest.EarnedOT, opt => opt.MapFrom(src => src.EarnedOT))
                .ForMember(dest => dest.IsAttBonus, opt => opt.MapFrom(src => src.IsAttBonus))
                .ForMember(dest => dest.EarnedAttBonus, opt => opt.MapFrom(src => src.EarnedAttBonus))
                .ForMember(dest => dest.IsHRAPerDay, opt => opt.MapFrom(src => src.IsHRAPerDay))
                .ForMember(dest => dest.IsHRAPerMonth, opt => opt.MapFrom(src => src.IsHRAPerMonth))
                .ForMember(dest => dest.HRA, opt => opt.MapFrom(src => src.HRA))
                .ForMember(dest => dest.EarnedHRA, opt => opt.MapFrom(src => src.EarnedHRA))
                .ForMember(dest => dest.IsTAPerDay, opt => opt.MapFrom(src => src.IsTAPerDay))
                .ForMember(dest => dest.IsTAPerMonth, opt => opt.MapFrom(src => src.IsTAPerMonth))
                .ForMember(dest => dest.TA, opt => opt.MapFrom(src => src.TA))
                .ForMember(dest => dest.EarnedTA, opt => opt.MapFrom(src => src.EarnedTA))
                .ForMember(dest => dest.EA, opt => opt.MapFrom(src => src.EA))
                .ForMember(dest => dest.SplAllow, opt => opt.MapFrom(src => src.SplAllow))
                .ForMember(dest => dest.EarnedSplAllow, opt => opt.MapFrom(src => src.EarnedSplAllow))
                .ForMember(dest => dest.LTA, opt => opt.MapFrom(src => src.LTA))
                .ForMember(dest => dest.MR, opt => opt.MapFrom(src => src.MR))
                .ForMember(dest => dest.TotalEarnings, opt => opt.MapFrom(src => src.TotalEarnings))
                .ForMember(dest => dest.IsPF, opt => opt.MapFrom(src => src.IsPF))
                .ForMember(dest => dest.EarnedPF, opt => opt.MapFrom(src => src.EarnedPF))
                .ForMember(dest => dest.IsESI, opt => opt.MapFrom(src => src.IsESI))
                .ForMember(dest => dest.EarnedESI, opt => opt.MapFrom(src => src.EarnedESI))
                .ForMember(dest => dest.PT, opt => opt.MapFrom(src => src.PT))
                .ForMember(dest => dest.TDS, opt => opt.MapFrom(src => src.TDS))
                .ForMember(dest => dest.Society, opt => opt.MapFrom(src => src.Society))
                .ForMember(dest => dest.Insurance, opt => opt.MapFrom(src => src.Insurance))
                .ForMember(dest => dest.SalAdvance, opt => opt.MapFrom(src => src.SalAdvance))
                .ForMember(dest => dest.Fines, opt => opt.MapFrom(src => src.Fines))
                .ForMember(dest => dest.DamageLoss, opt => opt.MapFrom(src => src.DamageLoss))
                .ForMember(dest => dest.OtherDed, opt => opt.MapFrom(src => src.OtherDed))
                .ForMember(dest => dest.LoanId, opt => opt.MapFrom(src => src.LoanId))
                .ForMember(dest => dest.LoanAmtDed, opt => opt.MapFrom(src => src.LoanAmtDed))
                .ForMember(dest => dest.LoanBalB4, opt => opt.MapFrom(src => src.LoanBalB4))
                .ForMember(dest => dest.TotalDed, opt => opt.MapFrom(src => src.TotalDed))
                .ForMember(dest => dest.NetPay, opt => opt.MapFrom(src => src.NetPay))
                .ForMember(dest => dest.OldBal, opt => opt.MapFrom(src => src.OldBal))
                .ForMember(dest => dest.paidAmt, opt => opt.MapFrom(src => src.paidAmt))
                .ForMember(dest => dest.AttBonus, opt => opt.MapFrom(src => src.AttBonus))
                .ForMember(dest => dest.LoanDedId, opt => opt.MapFrom(src => src.LoanDedId))
                .ForMember(dest => dest.IsDAtoPF, opt => opt.MapFrom(src => src.IsDAtoPF))
                .ForMember(dest => dest.IsPT, opt => opt.MapFrom(src => src.IsPT))
                .ForMember(dest => dest.ESIBankCode, opt => opt.MapFrom(src => src.ESIBankCode))
                .ForMember(dest => dest.ESIBankName, opt => opt.MapFrom(src => src.ESIBankName))
                .ForMember(dest => dest.ESICQDate, opt => opt.MapFrom(src => src.ESICQDate))
                .ForMember(dest => dest.ESICQNo, opt => opt.MapFrom(src => src.ESICQNo))
                .ForMember(dest => dest.ESIDate, opt => opt.MapFrom(src => src.ESIDate))
                .ForMember(dest => dest.ESIPytMode, opt => opt.MapFrom(src => src.ESIPytMode))
                .ForMember(dest => dest.PFBankName, opt => opt.MapFrom(src => src.PFBankName))
                .ForMember(dest => dest.PFCQDate, opt => opt.MapFrom(src => src.PFCQDate))
                .ForMember(dest => dest.PFCQNo, opt => opt.MapFrom(src => src.PFCQNo))
                .ForMember(dest => dest.PFDate, opt => opt.MapFrom(src => src.PFDate))
                .ForMember(dest => dest.PFDepositor, opt => opt.MapFrom(src => src.PFDepositor))
                .ForMember(dest => dest.PFPytMode, opt => opt.MapFrom(src => src.PFPytMode))
                .ForMember(dest => dest.Createdby, opt => opt.MapFrom(src => src.Createdby))
                .ForMember(dest => dest.Createddate, opt => opt.MapFrom(src => src.Createddate))
                .ForMember(dest => dest.Modifiedby, opt => opt.MapFrom(src => src.Modifiedby))
                .ForMember(dest => dest.Modifieddate, opt => opt.MapFrom(src => src.Modifieddate))
                .ForMember(dest => dest.chckOT, opt => opt.MapFrom(src => src.chckOT))
                .ForMember(dest => dest.PH, opt => opt.MapFrom(src => src.PH))
                .ForMember(dest => dest.W, opt => opt.MapFrom(src => src.W))
                .ForMember(dest => dest.LOP, opt => opt.MapFrom(src => src.LOP))
                .ForMember(dest => dest.P, opt => opt.MapFrom(src => src.P))
                .ForMember(dest => dest.O, opt => opt.MapFrom(src => src.O))
                .ForMember(dest => dest.Miscellaneous, opt => opt.MapFrom(src => src.Miscellaneous))
                .ForMember(dest => dest.Others, opt => opt.MapFrom(src => src.Others))
                .ForMember(dest => dest.IsSplAllowPerDay, opt => opt.MapFrom(src => src.IsSplAllowPerDay))
                .ForMember(dest => dest.IsMRPerDay, opt => opt.MapFrom(src => src.IsMRPerDay))
                .ForMember(dest => dest.IsLTAPerDay, opt => opt.MapFrom(src => src.IsLTAPerDay))
                .ForMember(dest => dest.IsEAPerDay, opt => opt.MapFrom(src => src.IsEAPerDay))
                .ForMember(dest => dest.IsSplAllowPerMonth, opt => opt.MapFrom(src => src.IsSplAllowPerMonth))
                .ForMember(dest => dest.IsMRPerMonth, opt => opt.MapFrom(src => src.IsMRPerMonth))
                .ForMember(dest => dest.IsLTAPerMonth, opt => opt.MapFrom(src => src.IsLTAPerMonth))
                .ForMember(dest => dest.IsEAPerMonth, opt => opt.MapFrom(src => src.IsEAPerMonth))
                .ForMember(dest => dest.EarnedLTA, opt => opt.MapFrom(src => src.EarnedLTA))
                .ForMember(dest => dest.EarnedMR, opt => opt.MapFrom(src => src.EarnedMR))
                .ForMember(dest => dest.EarnedEA, opt => opt.MapFrom(src => src.EarnedEA))
                .ForMember(dest => dest.PresentDays, opt => opt.MapFrom(src => src.PresentDays))
                .ForMember(dest => dest.AbsentDays, opt => opt.MapFrom(src => src.AbsentDays))
                .ForMember(dest => dest.Holidays, opt => opt.MapFrom(src => src.Holidays));
                //.ForAllOtherMembers(opt => opt.Ignore());
        }
    }
}
