<Project Sdk="Microsoft.NET.Sdk.Razor">
	
	<PropertyGroup>
      <TargetFrameworks>net9.0-windows10.0.19041.0;net9.0</TargetFrameworks>
      <Nullable>enable</Nullable>
      <ImplicitUsings>enable</ImplicitUsings>
      <LangVersion>latest</LangVersion>
    </PropertyGroup>
    
    <ItemGroup>
        <None Include="wwwroot\app.css" />
        <None Include="wwwroot\bootstrap\bootstrap.min.css" />
        <None Include="wwwroot\bootstrap\bootstrap.min.css.map" />
        <None Include="wwwroot\favicon.png" />
        <None Include="wwwroot\images\authorize-denied.jpg" />
        <None Include="wwwroot\images\bspllogo.jpg" />
        <None Include="wwwroot\images\BSPLLOGOANIMATED.gif" />
        <None Include="wwwroot\images\loading.gif" />
        <None Include="wwwroot\images\logout.jpg" />
        <None Include="wwwroot\js\autoSelect.js" />
        <None Include="wwwroot\js\common.js" />
        <None Include="wwwroot\js\isNumericWithDot.js" />
        <None Include="wwwroot\js\notification.js" />
    </ItemGroup>

  <ItemGroup>
    <SupportedPlatform Include="browser" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="16.1.1" />
    <PackageReference Include="Blazor-ApexCharts" Version="6.1.0" />
    <PackageReference Include="Blazored.LocalStorage" Version="4.5.0" />
    <PackageReference Include="BouncyCastle.Cryptography" Version="2.6.2" />
    <PackageReference Include="ClosedXML" Version="0.105.0" />
    <PackageReference Include="DocumentFormat.OpenXml" Version="3.3.0" />
    <PackageReference Include="EPPlus" Version="8.5.0" />
    <PackageReference Include="ExcelDataReader" Version="3.7.0" />
    <PackageReference Include="ExcelDataReader.DataSet" Version="3.7.0" />
    <PackageReference Include="FastReport.Data.MsSql" Version="2026.1.2" />
    <PackageReference Include="FastReport.OpenSource" Version="2026.1.2" />
    <PackageReference Include="FastReport.OpenSource.Export.PdfSimple" Version="2026.1.2" />
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.7.0" />
    <PackageReference Include="MailKit" Version="4.17.0" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Authorization" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.DataAnnotations.Validation" Version="3.2.0-rc1.20223.4" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Components.Web" Version="9.0.5" />
    <PackageReference Include="Microsoft.AspNetCore.Http.Abstractions" Version="2.3.0" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="9.0.5" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="9.0.5">
		
    <PrivateAssets>all</PrivateAssets>
    <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="MimeKit" Version="4.17.0" />
    <PackageReference Include="MudBlazor" Version="8.11.0" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
    <PackageReference Include="QRCoder" Version="1.7.0" />
    <PackageReference Include="ZXing.Net" Version="0.16.11" />
  </ItemGroup>

  <ItemGroup>
    <Service Include="{508349b6-6b84-4df5-91f0-309beebad82d}" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="BusinessLayer\BusinessService\IBusinessService\IInspectionService\" />
    <Folder Include="BusinessLayer\BusinessService\IBusinessService\IReportService\IHistory_Service\" />
    <Folder Include="BusinessLayer\BusinessService\IBusinessService\IReportService\IIssueSummaryService\" />
    <Folder Include="BusinessLayer\BusinessService\IBusinessService\IReportService\ITaxDetailsService\" />
    <Folder Include="BusinessLayer\BusinessService\IBusinessService\IServiceBillService\" />
    <Folder Include="BusinessLayer\BusinessService\IBusinessService\IAppVersion_Service\" />
    <Folder Include="BusinessLayer\BusinessService\ReportService\History_Service\" />
    <Folder Include="BusinessLayer\BusinessService\ReportService\IssueSummaryService\" />
    <Folder Include="BusinessLayer\BusinessService\ReportService\ProductionRptService\" />
    <Folder Include="BusinessLayer\BusinessService\ReportService\TaxDetailsService\" />
    <Folder Include="BusinessLayer\BusinessService\ServiceBillService\" />
    <Folder Include="Data\Inspection\DefectInfo\" />
    <Folder Include="Data\HumanResource\" />
    <Folder Include="Pages\Report_Module_Pages\AccountsRpt_Pages\" />
    <Folder Include="Pages\Report_Module_Pages\History_Pages\" />
    <Folder Include="Pages\Report_Module_Pages\Ratings_Pages\" />
    <Folder Include="Pages\Report_Module_Pages\TaxDet_Pages\" />
    <Folder Include="Pages\Report_Module_Pages\PoPending_Pages\" />
    <Folder Include="Repository\InspectionRepository\" />
    <Folder Include="Repository\IRepository\IInspectionRepository\" />
    <Folder Include="Services\IService\" />
    <Folder Include="ViewModels\InspectionViewModel\" />
    <Folder Include="ViewModels\ReportViewModel\AccountRptVM\" />
    <Folder Include="ViewModels\ReportViewModel\HistoryVM\" />
    <Folder Include="ViewModels\ReportViewModel\IssueSummaryVM\" />
    <Folder Include="ViewModels\ReportViewModel\GSTITC4\" />
    <Folder Include="ViewModels\ReportViewModel\RatingsVM\" />
    <Folder Include="ViewModels\ReportViewModel\TaxDetailsVM\" />
    <Folder Include="ViewModels\ReportViewModel\TrakReportsViewModel\PoPendingModel\" />
    <Folder Include="wwwroot\templates\default\" />
    <Folder Include="wwwroot\templates\acucom.bhargavisofttech.co.in\" />
    <Folder Include="wwwroot\templates\ByraveshwaraEnggEnts.bhargavisofttech.co.in\" />
    <Folder Include="wwwroot\templates\rrforgspl.bhargavisofttech.co.in\" />
  </ItemGroup>

</Project>